### PR TITLE
Configurable activeColor for radio buttons

### PR DESCRIPTION
**Pull request by Amitbhave**

### CODE REVIEW

**Comment by Amitbhave** [comment]
@TercyoStorck @danvick can you please review the same?

**Comment by pishguy** [comment]
@Amitbhave 

+1

**Comment by Amitbhave** [comment]
@MahdiPishguy unfortunately this doesn't seem to be active repository, as it has been over a month raising the PR still they haven't reviewed it.

**Comment by pishguy** [comment]
@Amitbhave we can fork this repository and work on that together

**Comment by Amitbhave** [comment]
@MahdiPishguy sure.. I will be happy to contribute and enhance this package further!

**Pull request merged**
